.PHONY: clean All

All:
	@echo "----------Building project:[ Symmetric_Matrix_CPP - Debug ]----------"
	@cd "Symmetric_Matrix_CPP" && "$(MAKE)" -f  "Symmetric_Matrix_CPP.mk"
clean:
	@echo "----------Cleaning project:[ Symmetric_Matrix_CPP - Debug ]----------"
	@cd "Symmetric_Matrix_CPP" && "$(MAKE)" -f  "Symmetric_Matrix_CPP.mk" clean
