.PHONY: clean All

All:
	@echo "----------Building project:[ Heap_Sort - Debug ]----------"
	@cd "Heap_Sort" && "$(MAKE)" -f  "Heap_Sort.mk"
clean:
	@echo "----------Cleaning project:[ Heap_Sort - Debug ]----------"
	@cd "Heap_Sort" && "$(MAKE)" -f  "Heap_Sort.mk" clean
