.PHONY: clean All

All:
	@echo "----------Building project:[ Merge_Sort_Recursive - Debug ]----------"
	@cd "Merge_Sort_Recursive" && "$(MAKE)" -f  "Merge_Sort_Recursive.mk"
clean:
	@echo "----------Cleaning project:[ Merge_Sort_Recursive - Debug ]----------"
	@cd "Merge_Sort_Recursive" && "$(MAKE)" -f  "Merge_Sort_Recursive.mk" clean
