.PHONY: clean All

All:
	@echo "----------Building project:[ Insertion_Sort - Debug ]----------"
	@cd "Insertion_Sort" && "$(MAKE)" -f  "Insertion_Sort.mk"
clean:
	@echo "----------Cleaning project:[ Insertion_Sort - Debug ]----------"
	@cd "Insertion_Sort" && "$(MAKE)" -f  "Insertion_Sort.mk" clean
