.PHONY: clean All

All:
	@echo "----------Building project:[ Sparse_Matrix - Debug ]----------"
	@cd "Sparse_Matrix" && "$(MAKE)" -f  "Sparse_Matrix.mk"
clean:
	@echo "----------Cleaning project:[ Sparse_Matrix - Debug ]----------"
	@cd "Sparse_Matrix" && "$(MAKE)" -f  "Sparse_Matrix.mk" clean
