.PHONY: clean All

All:
	@echo "----------Building project:[ Array_Delete - Debug ]----------"
	@cd "Array_Delete" && "$(MAKE)" -f  "Array_Delete.mk"
clean:
	@echo "----------Cleaning project:[ Array_Delete - Debug ]----------"
	@cd "Array_Delete" && "$(MAKE)" -f  "Array_Delete.mk" clean
