.PHONY: clean All

All:
	@echo "----------Building project:[ Linear_Search - Debug ]----------"
	@cd "Linear_Search" && "$(MAKE)" -f  "Linear_Search.mk"
clean:
	@echo "----------Cleaning project:[ Linear_Search - Debug ]----------"
	@cd "Linear_Search" && "$(MAKE)" -f  "Linear_Search.mk" clean
