.PHONY: clean All

All:
	@echo "----------Building project:[ Recursive_Insert_and_Delete_Binary_Search_Tree - Debug ]----------"
	@cd "Recursive_Insert_and_Delete_Binary_Search_Tree" && "$(MAKE)" -f  "Recursive_Insert_and_Delete_Binary_Search_Tree.mk"
clean:
	@echo "----------Cleaning project:[ Recursive_Insert_and_Delete_Binary_Search_Tree - Debug ]----------"
	@cd "Recursive_Insert_and_Delete_Binary_Search_Tree" && "$(MAKE)" -f  "Recursive_Insert_and_Delete_Binary_Search_Tree.mk" clean
