.PHONY: clean All

All:
	@echo "----------Building project:[ Display_Linked_List - Debug ]----------"
	@cd "Display_Linked_List" && "$(MAKE)" -f  "Display_Linked_List.mk"
clean:
	@echo "----------Cleaning project:[ Display_Linked_List - Debug ]----------"
	@cd "Display_Linked_List" && "$(MAKE)" -f  "Display_Linked_List.mk" clean
