.PHONY: clean All

All:
	@echo "----------Building project:[ Tree_CPP - Debug ]----------"
	@cd "Tree_CPP" && "$(MAKE)" -f  "Tree_CPP.mk"
clean:
	@echo "----------Cleaning project:[ Tree_CPP - Debug ]----------"
	@cd "Tree_CPP" && "$(MAKE)" -f  "Tree_CPP.mk" clean
