.PHONY: clean All

All:
	@echo "----------Building project:[ Stack_using_Array - Debug ]----------"
	@cd "Stack_using_Array" && "$(MAKE)" -f  "Stack_using_Array.mk"
clean:
	@echo "----------Cleaning project:[ Stack_using_Array - Debug ]----------"
	@cd "Stack_using_Array" && "$(MAKE)" -f  "Stack_using_Array.mk" clean
