.PHONY: clean All

All:
	@echo "----------Building project:[ Sparse_Matrix_using_Linked_List - Debug ]----------"
	@cd "Sparse_Matrix_using_Linked_List" && "$(MAKE)" -f  "Sparse_Matrix_using_Linked_List.mk"
clean:
	@echo "----------Cleaning project:[ Sparse_Matrix_using_Linked_List - Debug ]----------"
	@cd "Sparse_Matrix_using_Linked_List" && "$(MAKE)" -f  "Sparse_Matrix_using_Linked_List.mk" clean
