.PHONY: clean All

All:
	@echo "----------Building project:[ Finding_Duplicates_in_String_Hashing - Debug ]----------"
	@cd "Finding_Duplicates_in_String_Hashing" && "$(MAKE)" -f  "Finding_Duplicates_in_String_Hashing.mk"
clean:
	@echo "----------Cleaning project:[ Finding_Duplicates_in_String_Hashing - Debug ]----------"
	@cd "Finding_Duplicates_in_String_Hashing" && "$(MAKE)" -f  "Finding_Duplicates_in_String_Hashing.mk" clean
