.PHONY: clean All

All:
	@echo "----------Building project:[ AVL_Tree_RL_Rotation - Debug ]----------"
	@cd "AVL_Tree_RL_Rotation" && "$(MAKE)" -f  "AVL_Tree_RL_Rotation.mk"
clean:
	@echo "----------Cleaning project:[ AVL_Tree_RL_Rotation - Debug ]----------"
	@cd "AVL_Tree_RL_Rotation" && "$(MAKE)" -f  "AVL_Tree_RL_Rotation.mk" clean
