.PHONY: clean All

All:
	@echo "----------Building project:[ Kruskal_Algorithm - Debug ]----------"
	@cd "Kruskal_Algorithm" && "$(MAKE)" -f  "Kruskal_Algorithm.mk"
clean:
	@echo "----------Cleaning project:[ Kruskal_Algorithm - Debug ]----------"
	@cd "Kruskal_Algorithm" && "$(MAKE)" -f  "Kruskal_Algorithm.mk" clean
