.PHONY: clean All

All:
	@echo "----------Building project:[ Quadratic_Probing - Debug ]----------"
	@cd "Quadratic_Probing" && "$(MAKE)" -f  "Quadratic_Probing.mk"
clean:
	@echo "----------Cleaning project:[ Quadratic_Probing - Debug ]----------"
	@cd "Quadratic_Probing" && "$(MAKE)" -f  "Quadratic_Probing.mk" clean
