.PHONY: clean All

All:
	@echo "----------Building project:[ 2D_Arrays - Debug ]----------"
	@cd "2D_Arrays" && "$(MAKE)" -f  "2D_Arrays.mk"
clean:
	@echo "----------Cleaning project:[ 2D_Arrays - Debug ]----------"
	@cd "2D_Arrays" && "$(MAKE)" -f  "2D_Arrays.mk" clean
